config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  root to: 'static#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates_presence_of :title, :date, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Your blog was successfully created'
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @blog.delete
    redirect_to blogs_path, notice: 'Your blog was successfully deleted'
  end


  private

    def blog_params
      params.require(:blog).permit(:title, :date, :body)
    end

    def set_post
      @blog = Blog.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
    @blogs = Blog.all 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<%= render 'shared/nav' %>

<%= @blogs.inspect %>

app/views/blogs/new.html.erb
<%= render 'shared/nav' %>

<%= form_for @blog do |f| %>

  <%= f.text_field :title %>
  <%= f.date_field :date %>
  <%= f.text_area :body %>

  <%= f.submit 'Save' %>

<% end %>

app/views/blogs/show.html.erb
<h1>Show</h1>

<%= render 'shared/nav' %>

<%= @blog.inspect %>

<%= link_to 'Delete', blog_path(@blog), method: :delete, id: "delete_blog_#{@blog.id}_from_index", data: {confirm: 'You sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jan6Blogs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<div>
  <%= link_to 'Home', root_path, class: "btn btn-info" %>
  <%= link_to 'Blogs', blogs_path, class: "btn btn-info" %>
  <%= link_to "New Blog", new_blog_path, id: "new_blog_from_nav" %>
</div>






 